#!/usr/bin/env python3
from pathlib import Path
import csv, hashlib, json, re, sys, zipfile
try:
 import yaml
except Exception:
 yaml=None
ROOT=Path(__file__).resolve().parents[1]
EXPECTED_COUNT=402; BOOK_HASH='14eff00a111e9e985cc86e5e640cd9ae967f2e170e7d0768e765f80aa1c092d5'; PROOF_HASH='35bca9ce3809cc55a82bdd6e82548cf292458d32792aa10d3066d2aa3da1fa6a'; FIG_HASH='3c1ea05af05ce28d50195a86b27327c933a6fd719bf76158a60014e6834091ec'
errors=[]
def req(cond,msg):
 if not cond: errors.append(msg)
def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1048576),b''): h.update(b)
 return h.hexdigest()
files=[p for p in ROOT.rglob('*') if p.is_file() and '.git' not in p.relative_to(ROOT).parts]
req(len(files)==EXPECTED_COUNT,f'file count {len(files)} != {EXPECTED_COUNT}')
required=['README.md','VERSION','VERSION.txt','CITATION.cff','.zenodo.json','LICENSE-CODE','LICENSE-DOCUMENTATION.md','RIGHTS_AND_RELEASE_STATUS.md','manifests/FILE_CLASS_LICENCE_REGISTER.csv','manifests/REPOSITORY_MANIFEST.csv','manifests/REPOSITORY_MANIFEST.json','manifests/REPOSITORY_SHA256.txt','companion/04_TEMPLATES_FULL/SUBMISSION_PACKAGE_MANIFEST_FULL.csv','companion/07_SUBMISSION_AND_DEFENCE/CURRENT_SESSION_SUBMISSION_CONTROL.csv','companion/07_SUBMISSION_AND_DEFENCE/DC_E_SUBMISSION_AND_DEFENCE.md']
for rel in required: req((ROOT/rel).is_file(),'missing '+rel)
readme=(ROOT/'README.md').read_text(encoding='utf-8')
req('Student’s Guide to Research Projects, Theses and Dissertations' in readme,'canonical title missing')
req('From Topic Selection to Evidence, Implementation, Writing and Defence' in readme,'subtitle missing')
req('Antonio Clim and Martino Aldrigo' in readme,'associated book authors missing')
version=(ROOT/'VERSION.txt').read_text(encoding='utf-8')
req((ROOT/'VERSION').read_text(encoding='utf-8').strip()=='1.2.0','VERSION mismatch')
req(version.splitlines()[0].strip()=='1.2.0','VERSION.txt mismatch')
req(BOOK_HASH in version,'final book hash missing')
req(PROOF_HASH in version,'final proof hash missing')
req(FIG_HASH in version,'figure authority hash missing')
active_paths=['README.md','VERSION.txt','CITATION.cff','RIGHTS_AND_RELEASE_STATUS.md','docs/RELEASE_NOTES_1.2.0.md','companion/00_READ_FIRST/README.md','companion/00_READ_FIRST/RELEASE_STATUS.md','figures/README.md','figures/VERSION.txt']
active='\n'.join((ROOT/x).read_text(encoding='utf-8',errors='replace') for x in active_paths)
for token in ['PRIVATE REVIEW CANDIDATE','PUBLIC RELEASE HOLD','No public licence is granted','release remains prohibited','private hold','1.2.0-rc.4','v3.8.2']:
 req(token.lower() not in active.lower(),'active metadata retains '+token)
req('CC BY 4.0' in active,'CC BY 4.0 missing')
req('MIT' in active,'MIT missing')
req('10.5281/zenodo.' not in active,'unverified Zenodo DOI asserted')
if yaml:
 try:
  cff=yaml.safe_load((ROOT/'CITATION.cff').read_text(encoding='utf-8'))
  req(cff.get('version')=='1.2.0','CFF version mismatch')
  a=cff.get('authors') or []
  req(len(a)==1 and a[0].get('family-names')=='Clim' and a[0].get('given-names')=='Antonio','CFF creator mismatch')
  for k in ['doi','date-released','license']: req(k not in cff,'CFF prematurely asserts '+k)
 except Exception as e: errors.append('CFF parse: '+str(e))
else: errors.append('PyYAML unavailable')
z=json.loads((ROOT/'.zenodo.json').read_text(encoding='utf-8'))
req(len(z.get('creators',[]))==1 and z['creators'][0].get('name')=='Clim, Antonio','Zenodo creator mismatch')
req('doi' not in z and 'prereserve_doi' not in z,'Zenodo DOI prematurely asserted')
for p in files:
 rel=p.relative_to(ROOT).as_posix(); low=rel.lower()
 req('__pycache__' not in rel and not low.endswith('.pyc'),'generated bytecode included: '+rel)
 req(not rel.startswith('figures/00_AUTHOR_SUPPLIED_ODG_UNMODIFIED/'),'duplicated source ODG included: '+rel)
 req(not any(x in low for x in ['final_publisher_master','technical_proof','.eml','signed_form','correspondence','identity_document']),'private object included: '+rel)
 req('1.2.0-rc.4' not in rel,'active rc.4 filename included: '+rel)
fig=ROOT/'figures'
counts={e:len(list(fig.rglob('*'+e))) for e in ['.svg','.png','.odg','.pptx']}
req(counts=={'.svg':18,'.png':19,'.odg':19,'.pptx':19},'figure counts invalid '+str(counts))
wb=ROOT/'companion/01_WORKBOOK/COMPANION_WORKBOOK_v1.2.0.docx'
try:
 with zipfile.ZipFile(wb) as q:
  req('word/vbaProject.bin' not in q.namelist(),'workbook contains macros')
  txt='\n'.join(q.read(n).decode('utf-8','replace') for n in q.namelist() if n.endswith('.xml'))
  for token in ['PRIVATE REVIEW CANDIDATE','PUBLIC RELEASE HOLD','1.2.0-rc.4','v3.8.2']:
   req(token not in txt,'workbook retains '+token)
  req('PUBLIC RELEASE' in txt and 'CC BY 4.0' in txt and 'MIT' in txt,'workbook release or licence metadata missing')
except Exception as e: errors.append('workbook invalid: '+str(e))
# File-class licence register must map the mandated classes.
lic=(ROOT/'manifests/FILE_CLASS_LICENCE_REGISTER.csv').read_text(encoding='utf-8')
for token in ['CC BY 4.0','MIT','Workbook','Figure assets','Code and scripts','NOT DISTRIBUTED']:
 req(token in lic,'licence register missing '+token)
print(json.dumps({'status':'FAIL' if errors else 'PASS','file_count':len(files),'figure_counts':counts,'errors':errors},ensure_ascii=False,indent=2)); sys.exit(1 if errors else 0)
